import React, { useEffect, useState, useRef } from 'react';

import {
  SafeAreaView,
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  StatusBar,
ImageBackground,
PanResponder,  //
} from 'react-native';


type Verse = {
  text: string;
  reference: string;
};

const verses: Verse[] = [
  { text: "Be kind and compassionate to one another.", reference: "Ephesians 4:32" },
  { text: "Let your light shine before others.", reference: "Matthew 5:16" },
  { text: "When I am afraid, I put my trust in You.", reference: "Psalm 56:3" },
  { text: "The LORD is my shepherd; I shall not want.", reference: "Psalm 23:1" },
  { text: "I can do all things through Christ who gives me strength.", reference: "Philippians 4:13" },
  { text: "Love one another as I have loved you.", reference: "John 13:34" },
  { text: "Children, obey your parents in the Lord.", reference: "Ephesians 6:1" },
  { text: "Cast all your cares upon Him, for He cares for you.", reference: "1 Peter 5:7" },
  { text: "Trust in the Lord with all your heart.", reference: "Proverbs 3:5" },
  { text: "This is the day the Lord has made; we will rejoice and be glad in it.", reference: "Psalm 118:24" },
  { text: "Do everything in love.", reference: "1 Corinthians 16:14" },
  { text: "A friend loves at all times.", reference: "Proverbs 17:17" },
  { text: "In the beginning God created the heavens and the earth.", reference: "Genesis 1:1" },
  { text: "The Lord will fight for you; you need only be still.", reference: "Exodus 14:14" },
  { text: "The Lord bless you and keep you.", reference: "Numbers 6:24" },
  { text: "Be strong and courageous. Do not be afraid.", reference: "Joshua 1:9" },
  { text: "As for me and my house, we will serve the Lord.", reference: "Joshua 24:15" },
  { text: "The joy of the Lord is your strength.", reference: "Nehemiah 8:10" },
  { text: "Your word is a lamp to my feet and a light to my path.", reference: "Psalm 119:105" },
  { text: "Give thanks to the Lord for He is good.", reference: "Psalm 107:1" },
  { text: "Let everything that has breath praise the Lord.", reference: "Psalm 150:6" },
  { text: "God is our refuge and strength.", reference: "Psalm 46:1" },
  { text: "Be still, and know that I am God.", reference: "Psalm 46:10" },
  { text: "The Lord is near to all who call on Him.", reference: "Psalm 145:18" },
  { text: "He heals the brokenhearted.", reference: "Psalm 147:3" },
  { text: "The name of the Lord is a strong tower.", reference: "Proverbs 18:10" },
  { text: "The fear of the Lord is the beginning of wisdom.", reference: "Proverbs 9:10" },
  { text: "As iron sharpens iron, so one person sharpens another.", reference: "Proverbs 27:17" },
  { text: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
  { text: "Call to Me and I will answer you.", reference: "Jeremiah 33:3" },
  { text: "The Lord is good to those who hope in Him.", reference: "Lamentations 3:25" },
  { text: "For with God nothing will be impossible.", reference: "Luke 1:37" },
  { text: "Love your neighbor as yourself.", reference: "Mark 12:31" },
  { text: "Everything is possible for one who believes.", reference: "Mark 9:23" },
  { text: "For God so loved the world that He gave His only Son.", reference: "John 3:16" },
  { text: "If the Son sets you free, you will be free indeed.", reference: "John 8:36" },
  { text: "My peace I give you.", reference: "John 14:27" },
  { text: "We love because He first loved us.", reference: "1 John 4:19" },
  { text: "God is love.", reference: "1 John 4:8" },
  { text: "Set your minds on things above.", reference: "Colossians 3:2" },
  { text: "Let the peace of Christ rule in your hearts.", reference: "Colossians 3:15" },
  { text: "Do everything in love.", reference: "1 Corinthians 16:14" },
  { text: "Pray without ceasing.", reference: "1 Thessalonians 5:17" },
  { text: "Rejoice always.", reference: "1 Thessalonians 5:16" },
  { text: "Therefore encourage one another.", reference: "1 Thessalonians 5:11" },
  { text: "Be strong in the Lord and in His mighty power.", reference: "Ephesians 6:10" },
  { text: "The Lord is my helper; I will not be afraid.", reference: "Hebrews 13:6" },
  { text: "He will never leave you nor forsake you.", reference: "Deuteronomy 31:6" },
  { text: "The Lord is my strength and my shield.", reference: "Psalm 28:7" },
  { text: "Taste and see that the Lord is good.", reference: "Psalm 34:8" },
  { text: "The Lord watches over all who love Him.", reference: "Psalm 145:20" },
  { text: "The Lord upholds all who fall.", reference: "Psalm 145:14" },
  { text: "Commit your way to the Lord; trust in Him.", reference: "Psalm 37:5" },
  { text: "The Lord is good, a safe place in times of trouble.", reference: "Nahum 1:7" },
  { text: "He will quiet you with His love.", reference: "Zephaniah 3:17" },
  { text: "He will rejoice over you with singing.", reference: "Zephaniah 3:17" },
  { text: "The Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
  { text: "Seek the Lord and His strength.", reference: "1 Chronicles 16:11" },
  { text: "Give thanks to the Lord and call on His name.", reference: "1 Chronicles 16:8" },
  { text: "Be strong and do not give up, for your work will be rewarded.", reference: "2 Chronicles 15:7" },
  { text: "The Lord searches every heart and understands every desire.", reference: "1 Chronicles 28:9" },
  { text: "The Lord will not forsake His people.", reference: "Psalm 94:14" },
  { text: "The Lord is gracious and full of compassion.", reference: "Psalm 145:8" },
  { text: "He crowns you with love and compassion.", reference: "Psalm 103:4" },
  { text: "From everlasting to everlasting the Lord's love is with those who fear Him.", reference: "Psalm 103:17" },
  { text: "Those who seek the Lord lack no good thing.", reference: "Psalm 34:10" },
  { text: "The Lord gives wisdom.", reference: "Proverbs 2:6" },
  { text: "In all your ways acknowledge Him, and He will make your paths straight.", reference: "Proverbs 3:6" },
  { text: "The righteous are as bold as a lion.", reference: "Proverbs 28:1" },
  { text: "A gentle answer turns away anger.", reference: "Proverbs 15:1" },
  { text: "A faithful friend is a strong shelter.", reference: "Proverbs 18:24" },
  { text: "The Lord delights in people who are honest.", reference: "Proverbs 12:22" },
  { text: "The eyes of the Lord are everywhere, keeping watch.", reference: "Proverbs 15:3" },
  { text: "He gives strength to the weary and power to the weak.", reference: "Isaiah 40:29" },
  { text: "Those who hope in the Lord will renew their strength.", reference: "Isaiah 40:31" },
  { text: "When you pass through the waters, I will be with you.", reference: "Isaiah 43:2" },
  { text: "I have called you by name; you are Mine.", reference: "Isaiah 43:1" },
  { text: "As a mother comforts her child, so I will comfort you.", reference: "Isaiah 66:13" },
  { text: "The Lord your God is with you; He is mighty to save.", reference: "Zephaniah 3:17" },
  { text: "The Lord is slow to anger and great in power.", reference: "Nahum 1:3" },
  { text: "Return to the Lord your God, for He is gracious and compassionate.", reference: "Joel 2:13" },
  { text: "The Lord is good; His love endures forever.", reference: "Psalm 100:5" },
  { text: "Serve the Lord with gladness.", reference: "Psalm 100:2" },
  { text: "Shout for joy to the Lord, all the earth.", reference: "Psalm 100:1" },
  { text: "The Lord gives His people peace.", reference: "Psalm 29:11" },
  { text: "The Lord is near to the brokenhearted.", reference: "Psalm 34:18" },
  { text: "Cast your cares on the Lord and He will sustain you.", reference: "Psalm 55:22" },
  { text: "The Lord is my rock and my fortress and my deliverer.", reference: "Psalm 18:2" },
  { text: "You are my hiding place; You protect me from trouble.", reference: "Psalm 32:7" },
  { text: "Teach me to do Your will, for You are my God.", reference: "Psalm 143:10" },
  { text: "Create in me a clean heart, O God.", reference: "Psalm 51:10" },
  { text: "Open my eyes that I may see wonderful things in Your law.", reference: "Psalm 119:18" },
  { text: "Blessed are those who hear the word of God and obey it.", reference: "Luke 11:28" },
  { text: "Let the word of Christ live in you richly.", reference: "Colossians 3:16" },
  { text: "Whatever you do, do it all in the name of the Lord Jesus.", reference: "Colossians 3:17" },
  { text: "Do not be overcome by evil, but overcome evil with good.", reference: "Romans 12:21" },
  { text: "Be joyful in hope, patient in trouble, faithful in prayer.", reference: "Romans 12:12" },
  { text: "If God is for us, who can be against us?", reference: "Romans 8:31" },
  { text: "The Lord is near to all who call on Him in truth.", reference: "Psalm 145:18" },
  { text: "The Lord sustains the humble.", reference: "Psalm 147:6" },
  { text: "He will cover you with His feathers.", reference: "Psalm 91:4" },
  { text: "The Lord is my fortress, my God in whom I trust.", reference: "Psalm 91:2" },
  { text: "God is our refuge and strength, an ever-present help in trouble.", reference: "Psalm 46:1" },
  { text: "The Lord gives rest to the weary.", reference: "Matthew 11:28" },
  { text: "Let the little children come to me.", reference: "Matthew 19:14" },
  { text: "Love your enemies and pray for those who hurt you.", reference: "Matthew 5:44" },
  { text: "Blessed are the pure in heart, for they will see God.", reference: "Matthew 5:8" },
  { text: "Blessed are the merciful, for they will be shown mercy.", reference: "Matthew 5:7" },
  { text: "A city on a hill cannot be hidden.", reference: "Matthew 5:14" },
  { text: "Ask and it will be given to you; seek and you will find.", reference: "Matthew 7:7" },
  { text: "With God all things are possible.", reference: "Matthew 19:26" },
  { text: "Do not let your hearts be troubled.", reference: "John 14:1" },
  { text: "I am the way, the truth, and the life.", reference: "John 14:6" },
  { text: "I give them eternal life, and they shall never perish.", reference: "John 10:28" },
  { text: "I am the good shepherd.", reference: "John 10:11" },
  { text: "Let not your hearts be troubled, neither let them be afraid.", reference: "John 14:27" },
  { text: "You are my friends if you do what I command.", reference: "John 15:14" },
  { text: "This is my command: Love one another.", reference: "John 15:17" },
  { text: "The Spirit helps us in our weakness.", reference: "Romans 8:26" },
  { text: "Nothing can separate us from the love of God.", reference: "Romans 8:39" },
  { text: "Be transformed by the renewing of your mind.", reference: "Romans 12:2" },
  { text: "Live in harmony with one another.", reference: "Romans 12:16" },
  { text: "Be joyful in hope, patient in affliction, faithful in prayer.", reference: "Romans 12:12" },
  { text: "Do not be overcome by evil, but overcome evil with good.", reference: "Romans 12:21" },
  { text: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
  { text: "Thanks be to God for His indescribable gift!", reference: "2 Corinthians 9:15" },
  { text: "Do everything without grumbling or arguing.", reference: "Philippians 2:14" },
  { text: "God will meet all your needs.", reference: "Philippians 4:19" },
  { text: "Let your gentleness be evident to all.", reference: "Philippians 4:5" },
  { text: "Set your minds on things above.", reference: "Colossians 3:2" },
  { text: "Let the peace of Christ rule in your hearts.", reference: "Colossians 3:15" },
  { text: "Clothe yourselves with compassion, kindness, humility.", reference: "Colossians 3:12" },
  { text: "Be completely humble and gentle.", reference: "Ephesians 4:2" },
  { text: "Children, obey your parents in everything.", reference: "Colossians 3:20" },
  { text: "Encourage one another daily.", reference: "Hebrews 3:13" },
  { text: "Jesus Christ is the same yesterday, today, and forever.", reference: "Hebrews 13:8" },
  { text: "Let us hold unswervingly to the hope we profess.", reference: "Hebrews 10:23" },
  { text: "The Lord is my helper; I will not be afraid.", reference: "Hebrews 13:6" },
  { text: "Every good and perfect gift is from above.", reference: "James 1:17" },
  { text: "Draw near to God and He will draw near to you.", reference: "James 4:8" },
  { text: "Cast all your anxiety on Him because He cares for you.", reference: "1 Peter 5:7" },
  { text: "Be alert and of sober mind.", reference: "1 Peter 5:8" },
  { text: "We love because He first loved us.", reference: "1 John 4:19" },
  { text: "Let us love one another, for love comes from God.", reference: "1 John 4:7" },
  { text: "God is greater than our hearts.", reference: "1 John 3:20" },
  { text: "The Lord will be your everlasting light.", reference: "Isaiah 60:19" },
  { text: "You will keep in perfect peace those whose minds are steadfast.", reference: "Isaiah 26:3" },
  { text: "The Lord goes before you and will be with you.", reference: "Deuteronomy 31:8" },
  { text: "He will strengthen you and help you.", reference: "Isaiah 41:10" },
  { text: "The Lord will keep you from all harm.", reference: "Psalm 121:7" },
  { text: "The Lord watches over your coming and going.", reference: "Psalm 121:8" },
  { text: "I will instruct you and teach you in the way you should go.", reference: "Psalm 32:8" },
  { text: "The Lord makes firm the steps of the one who delights in Him.", reference: "Psalm 37:23" },
  { text: "You are my strength; I sing praise to You.", reference: "Psalm 59:17" },
  { text: "My flesh and my heart may fail, but God is the strength of my heart.", reference: "Psalm 73:26" },
  { text: "The Lord is compassionate and gracious.", reference: "Psalm 103:8" },
  { text: "Praise the Lord, my soul, and forget not all His benefits.", reference: "Psalm 103:2" },
  { text: "He forgives all your sins and heals all your diseases.", reference: "Psalm 103:3" },
  { text: "He redeems your life from the pit.", reference: "Psalm 103:4" },
  { text: "The Lord works righteousness and justice.", reference: "Psalm 103:6" },
  { text: "The Lord has compassion on those who fear Him.", reference: "Psalm 103:13" },
  { text: "Blessed is the one who trusts in the Lord.", reference: "Jeremiah 17:7" },
  { text: "Call to Me and I will answer you.", reference: "Jeremiah 33:3" },
  { text: "The steadfast love of the Lord never ceases.", reference: "Lamentations 3:22" },
  { text: "His mercies are new every morning.", reference: "Lamentations 3:23" },
  { text: "The Lord is good to those who hope in Him.", reference: "Lamentations 3:25" },
  { text: "Seek justice, love mercy, walk humbly with your God.", reference: "Micah 6:8" },
  { text: "The Lord your God is with you, mighty to save.", reference: "Zephaniah 3:17" },
  { text: "He rejoices over you with singing.", reference: "Zephaniah 3:17" },
  { text: "The Lord is good, a refuge in times of trouble.", reference: "Nahum 1:7" },
  { text: "The Lord is slow to anger and great in power.", reference: "Nahum 1:3" },
  { text: "Let the weak say, ‘I am strong.’", reference: "Joel 3:10" },
  { text: "Yet I will rejoice in the Lord.", reference: "Habakkuk 3:18" },
  { text: "Is anything too hard for the Lord?", reference: "Genesis 18:14" },
  { text: "The Lord remembered Noah.", reference: "Genesis 8:1" },
  { text: "The Lord was with Joseph and gave him success.", reference: "Genesis 39:2" },
  { text: "The Lord will fight for you.", reference: "Exodus 14:14" },
  { text: "The joy of the Lord is your strength.", reference: "Nehemiah 8:10" },
  { text: "Those who know Your name trust in You.", reference: "Psalm 9:10" },
  { text: "The heavens declare the glory of God.", reference: "Psalm 19:1" },
  { text: "May He give you the desires of your heart.", reference: "Psalm 20:4" },
  { text: "The Lord gives strength to His people.", reference: "Psalm 29:11" },
  { text: "The Lord is close to the brokenhearted.", reference: "Psalm 34:18" },
  { text: "Taste and see that the Lord is good.", reference: "Psalm 34:8" },
  { text: "The Lord rescues His servants.", reference: "Psalm 34:22" },
  { text: "Commit your way to the Lord.", reference: "Psalm 37:5" },
  { text: "Be still before the Lord and wait patiently for Him.", reference: "Psalm 37:7" },
  { text: "The Lord delights in the way of the faithful.", reference: "Psalm 37:23" },
  { text: "The Lord is my refuge and strength.", reference: "Psalm 46:1" },
  { text: "God is within her; she will not fall.", reference: "Psalm 46:5" },
  { text: "Cast your cares on the Lord.", reference: "Psalm 55:22" },
  { text: "Your love, Lord, reaches to the heavens.", reference: "Psalm 36:5" },
  { text: "The Lord will fulfill His purpose for me.", reference: "Psalm 138:8" },
  { text: "The Lord lifts up those who are bowed down.", reference: "Psalm 146:8" },
  { text: "The Lord watches over all who love Him.", reference: "Psalm 145:20" },
  { text: "The Lord upholds all who fall.", reference: "Psalm 145:14" },
  { text: "He heals the brokenhearted.", reference: "Psalm 147:3" },
  { text: "He determines the number of the stars.", reference: "Psalm 147:4" },
  { text: "Great is our Lord and mighty in power.", reference: "Psalm 147:5" },
  { text: "Praise the Lord from the heavens.", reference: "Psalm 148:1" },
  { text: "Let everything that has breath praise the Lord.", reference: "Psalm 150:6" },
  { text: "Blessed is the one who does not walk in step with the wicked.", reference: "Psalm 1:1" },
  { text: "The Lord watches over the way of the righteous.", reference: "Psalm 1:6" },
  { text: "I will lie down and sleep in peace.", reference: "Psalm 4:8" },
  { text: "You have filled my heart with joy.", reference: "Psalm 4:7" },
  { text: "The Lord is a shield around me.", reference: "Psalm 3:3" },
  { text: "I will give thanks to the Lord because of His righteousness.", reference: "Psalm 7:17" },
  { text: "Lord, our Lord, how majestic is Your name.", reference: "Psalm 8:1" },
  { text: "Those who seek the Lord lack no good thing.", reference: "Psalm 34:10" },
  { text: "The Lord makes His face shine on you and be gracious to you.", reference: "Numbers 6:25" },
  { text: "The Lord turn His face toward you and give you peace.", reference: "Numbers 6:26" },
  { text: "Deal with everyone as you would like them to deal with you.", reference: "Luke 6:31" },
  { text: "Whoever can be trusted with little can be trusted with much.", reference: "Luke 16:10" },
  { text: "My grace is sufficient for you.", reference: "2 Corinthians 12:9" },
  { text: "Be completely humble and gentle; be patient.", reference: "Ephesians 4:2" },
  { text: "Be kind and compassionate to one another.", reference: "Ephesians 4:32" },
  { text: "Children, obey your parents in the Lord.", reference: "Ephesians 6:1" },
  { text: "Put on the full armor of God.", reference: "Ephesians 6:11" },
  { text: "The Lord will rescue me from every evil attack.", reference: "2 Timothy 4:18" },
  { text: "Let us run with perseverance the race marked out for us.", reference: "Hebrews 12:1" },
  { text: "Faith is confidence in what we hope for.", reference: "Hebrews 11:1" },
  { text: "Keep your lives free from the love of money.", reference: "Hebrews 13:5" },
  { text: "Let us consider how we may spur one another on.", reference: "Hebrews 10:24" },
  { text: "Every good and perfect gift is from above.", reference: "James 1:17" },
  { text: "Humble yourselves before the Lord.", reference: "James 4:10" },
  { text: "The prayer of a righteous person is powerful and effective.", reference: "James 5:16" },
  { text: "Cast all your anxiety on Him because He cares for you.", reference: "1 Peter 5:7" },
  { text: "Show proper respect to everyone.", reference: "1 Peter 2:17" },
  { text: "Love one another deeply, from the heart.", reference: "1 Peter 1:22" },
  { text: "Let us not love with words but with actions.", reference: "1 John 3:18" },
  { text: "God is greater than our hearts.", reference: "1 John 3:20" },
  { text: "We love because He first loved us.", reference: "1 John 4:19" },
  { text: "Let your light shine before others.", reference: "Matthew 5:16" },
  { text: "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom.", reference: "Luke 12:32" },
  { text: "The Lord is faithful, and He will strengthen you.", reference: "2 Thessalonians 3:3" },
  { text: "Stand firm in the faith; be courageous; be strong.", reference: "1 Corinthians 16:13" },
  { text: "The Lord is my portion, says my soul.", reference: "Lamentations 3:24" },
  { text: "Teach us to number our days.", reference: "Psalm 90:12" },
  { text: "Heaven and earth will pass away, but my words will never pass away.", reference: "Matthew 24:35" },
  { text: "The Lord blesses His people with peace.", reference: "Psalm 29:11" },
  { text: "Hold fast to what is good.", reference: "1 Thessalonians 5:21" },
  { text: "Let the righteous rejoice in the Lord.", reference: "Psalm 64:10" },
  { text: "The Lord will save me; He will lift me up.", reference: "Isaiah 38:20" },
  { text: "I will trust and not be afraid.", reference: "Isaiah 12:2" },
  { text: "God comforts us in all our troubles.", reference: "2 Corinthians 1:4" },
  { text: "The Lord is good; His love endures forever.", reference: "Psalm 100:5" },
  { text: "Serve the Lord with gladness.", reference: "Psalm 100:2" },
  { text: "The faithful love of the Lord never ends.", reference: "Lamentations 3:22" },
  { text: "Be strong and take heart, all you who hope in the Lord.", reference: "Psalm 31:24" },
  { text: "The Lord has done great things for us.", reference: "Psalm 126:3" },
  { text: "My help comes from the Lord.", reference: "Psalm 121:2" },
  { text: "The Lord will watch over your life.", reference: "Psalm 121:7" },
  { text: "I sought the Lord and He answered me.", reference: "Psalm 34:4" },
  { text: "The Lord is my light and my salvation.", reference: "Psalm 27:1" },
  { text: "One thing I ask of the Lord…", reference: "Psalm 27:4" },
  { text: "Wait for the Lord; be strong and take heart.", reference: "Psalm 27:14" },
  { text: "The Lord is close to the brokenhearted.", reference: "Psalm 34:18" },
  { text: "The angel of the Lord encamps around those who fear Him.", reference: "Psalm 34:7" },
  { text: "Taste and see that the Lord is good.", reference: "Psalm 34:8" },
  { text: "Blessed is the one whose hope is in the Lord.", reference: "Psalm 146:5" },
  { text: "He gives food to every creature.", reference: "Psalm 136:25" },
  { text: "Give thanks to the Lord, for He is good.", reference: "Psalm 136:1" },
  { text: "The Lord keeps all His promises.", reference: "Psalm 145:13" },
  { text: "The Lord is gracious and compassionate.", reference: "Psalm 145:8" },
  { text: "The Lord upholds all who fall.", reference: "Psalm 145:14" },
  { text: "The Lord watches over all who love Him.", reference: "Psalm 145:20" },
  { text: "Trust in Him at all times.", reference: "Psalm 62:8" },
  { text: "The Lord bestows favor and honor.", reference: "Psalm 84:11" },
  { text: "Better is one day in Your courts.", reference: "Psalm 84:10" },
  { text: "The Lord gives grace and glory.", reference: "Psalm 84:11" },
  { text: "Teach me Your way, Lord.", reference: "Psalm 86:11" },
  { text: "Great is Your love toward me.", reference: "Psalm 86:13" },
  { text: "You, Lord, are forgiving and good.", reference: "Psalm 86:5" },
  { text: "The Lord is my portion.", reference: "Lamentations 3:24" },
  { text: "In quietness and trust is your strength.", reference: "Isaiah 30:15" },
  { text: "Those who hope in the Lord will renew their strength.", reference: "Isaiah 40:31" },
  { text: "The Lord gives strength to His people.", reference: "Psalm 29:11" },
  { text: "He will quiet you with His love.", reference: "Zephaniah 3:17" },
  { text: "He rejoices over you with singing.", reference: "Zephaniah 3:17" },
  { text: "The Lord your God is with you.", reference: "Joshua 1:9" },
  { text: "Be strong and courageous.", reference: "Joshua 1:9" },
  { text: "Do not fear, for I am with you.", reference: "Isaiah 41:10" },
  { text: "I will never leave you nor forsake you.", reference: "Deuteronomy 31:6" },
  { text: "The Lord will fight for you.", reference: "Exodus 14:14" },
  { text: "God is our refuge and strength.", reference: "Psalm 46:1" },
  { text: "Be still and know that I am God.", reference: "Psalm 46:10" },
  { text: "The Lord is my helper.", reference: "Hebrews 13:6" },
  { text: "The Lord will watch over your coming and going.", reference: "Psalm 121:8" },
  { text: "He restores my soul.", reference: "Psalm 23:3" },
  { text: "Surely goodness and mercy will follow me.", reference: "Psalm 23:6" },
  { text: "Blessed are the peacemakers.", reference: "Matthew 5:9" },
  { text: "Blessed are the pure in heart.", reference: "Matthew 5:8" },
  { text: "Blessed are the merciful.", reference: "Matthew 5:7" },
  { text: "Let your light shine before others.", reference: "Matthew 5:16" },
  { text: "Ask and it will be given to you.", reference: "Matthew 7:7" },
  { text: "Love your neighbor as yourself.", reference: "Mark 12:31" },
  { text: "With God all things are possible.", reference: "Matthew 19:26" },
  { text: "Do to others as you would have them do to you.", reference: "Luke 6:31" },
  { text: "Whoever can be trusted with little can be trusted with much.", reference: "Luke 16:10" },
  { text: "My peace I give you.", reference: "John 14:27" },
  { text: "Do not let your hearts be troubled.", reference: "John 14:1" },
  { text: "I am the good shepherd.", reference: "John 10:11" },
  { text: "We love because He first loved us.", reference: "1 John 4:19" },
  { text: "God is love.", reference: "1 John 4:8" },
  { text: "Let us love one another.", reference: "1 John 4:7" },
  { text: "The Lord is faithful, and He will strengthen you.", reference: "2 Thessalonians 3:3" },
  { text: "Rejoice always.", reference: "1 Thessalonians 5:16" },
  { text: "Pray without ceasing.", reference: "1 Thessalonians 5:17" },
  { text: "Give thanks in all circumstances.", reference: "1 Thessalonians 5:18" },
  { text: "Let us not grow weary in doing good.", reference: "Galatians 6:9" },
  { text: "Children, obey your parents in the Lord.", reference: "Ephesians 6:1" },
  { text: "Be kind to one another, tenderhearted.", reference: "Ephesians 4:32" },
  { text: "Cloth yourselves with compassion, kindness, humility.", reference: "Colossians 3:12" },
  { text: "Whatever you do, do it all in the name of the Lord Jesus.", reference: "Colossians 3:17" },
  { text: "Let the peace of Christ rule in your hearts.", reference: "Colossians 3:15" },
  { text: "Set your minds on things above.", reference: "Colossians 3:2" },
  { text: "Do everything in love.", reference: "1 Corinthians 16:14" },
  { text: "Love is patient, love is kind.", reference: "1 Corinthians 13:4" },
  { text: "Love never fails.", reference: "1 Corinthians 13:8" },
  { text: "Be strong in the Lord.", reference: "Ephesians 6:10" },
  { text: "For by grace you have been saved.", reference: "Ephesians 2:8" },
  { text: "The Lord will give you rest.", reference: "Exodus 33:14" },
  { text: "The joy of the Lord is your strength.", reference: "Nehemiah 8:10" },
  { text: "The Lord is my portion.", reference: "Lamentations 3:24" },
  { text: "He has made everything beautiful in its time.", reference: "Ecclesiastes 3:11" },
  { text: "Two are better than one.", reference: "Ecclesiastes 4:9" },
  { text: "The Lord bless you and keep you.", reference: "Numbers 6:24" },
  { text: "The Lord make His face shine on you.", reference: "Numbers 6:25" },
  { text: "The Lord give you peace.", reference: "Numbers 6:26" },
  { text: "The Lord is slow to anger and rich in love.", reference: "Psalm 145:8" },
  { text: "Great is the Lord and greatly to be praised.", reference: "Psalm 48:1" },
  { text: "Your word is a lamp to my feet.", reference: "Psalm 119:105" },
  { text: "I have hidden Your word in my heart.", reference: "Psalm 119:11" },
  { text: "Open my eyes that I may see wonderful things.", reference: "Psalm 119:18" },
  { text: "The unfolding of Your words gives light.", reference: "Psalm 119:130" },
  { text: "The Lord keeps your foot from slipping.", reference: "Psalm 121:3" },
  { text: "Bless the Lord, O my soul.", reference: "Psalm 103:1" },
  { text: "You are my hiding place.", reference: "Psalm 32:7" },
  { text: "The Lord is my rock and my fortress.", reference: "Psalm 18:2" },
  { text: "The Lord is righteous in all His ways.", reference: "Psalm 145:17" },
  { text: "Be glad in the Lord and rejoice.", reference: "Psalm 32:11" },
  { text: "Let everything that has breath praise the Lord.", reference: "Psalm 150:6" },
  { text: "Blessed are those who hunger for righteousness.", reference: "Matthew 5:6" },
  { text: "Come to Me, and I will give you rest.", reference: "Matthew 11:28" },
  { text: "He will wipe every tear from their eyes.", reference: "Revelation 21:4" },
  { text: "I am making everything new!", reference: "Revelation 21:5" },
{ text: "The Lord is my strength and my shield.", reference: "Psalm 28:7" },
{ text: "The Lord gives wisdom.", reference: "Proverbs 2:6" },
{ text: "He guards the paths of the just.", reference: "Proverbs 2:8" },
{ text: "Trust in Him at all times.", reference: "Psalm 62:8" },
{ text: "My soul finds rest in God alone.", reference: "Psalm 62:1" },
{ text: "The Lord surrounds His people.", reference: "Psalm 125:2" },
{ text: "The Lord is righteous; He loves justice.", reference: "Psalm 11:7" },
{ text: "Those who seek the Lord lack no good thing.", reference: "Psalm 34:10" },
{ text: "The Lord is a refuge for the oppressed.", reference: "Psalm 9:9" },
{ text: "He will not let your foot slip.", reference: "Psalm 121:3" },
{ text: "My help comes from the Lord.", reference: "Psalm 121:2" },
{ text: "He will command His angels concerning you.", reference: "Psalm 91:11" },
{ text: "Under His wings you will find refuge.", reference: "Psalm 91:4" },
{ text: "The Lord is good to all.", reference: "Psalm 145:9" },
{ text: "Commit to the Lord whatever you do.", reference: "Proverbs 16:3" },
{ text: "The Lord detests lying lips.", reference: "Proverbs 12:22" },
{ text: "A gentle answer turns away wrath.", reference: "Proverbs 15:1" },
{ text: "The Lord is near to the brokenhearted.", reference: "Psalm 34:18" },
{ text: "The Lord upholds all who fall.", reference: "Psalm 145:14" },
{ text: "The Lord watches over all who love Him.", reference: "Psalm 145:20" },
{ text: "If you seek Him, He will be found by you.", reference: "1 Chronicles 28:9" },
{ text: "The Lord gives victory to His anointed.", reference: "Psalm 20:6" },
{ text: "He alone is my rock and my salvation.", reference: "Psalm 62:2" },
{ text: "The Lord disciplines those He loves.", reference: "Proverbs 3:12" },
{ text: "The Lord hears when I call to Him.", reference: "Psalm 4:3" },
{ text: "The Lord will keep you from all harm.", reference: "Psalm 121:7" },
{ text: "He will strengthen you and help you.", reference: "Isaiah 41:10" },
{ text: "He will give you the desires of your heart.", reference: "Psalm 37:4" },
{ text: "The Lord makes firm the steps of the one who delights in Him.", reference: "Psalm 37:23" },
{ text: "The Lord is faithful to all His promises.", reference: "Psalm 145:13" },
{ text: "I sought the Lord, and He answered me.", reference: "Psalm 34:4" },
{ text: "The Lord is my rock, my fortress, and my deliverer.", reference: "Psalm 18:2" },
{ text: "Let the peace of Christ rule in your hearts.", reference: "Colossians 3:15" },
{ text: "Whatever you do, work at it with all your heart.", reference: "Colossians 3:23" },
{ text: "Do not be anxious about anything.", reference: "Philippians 4:6" },
{ text: "The peace of God will guard your hearts and minds.", reference: "Philippians 4:7" },
{ text: "My God will meet all your needs.", reference: "Philippians 4:19" },
{ text: "Do everything without grumbling.", reference: "Philippians 2:14" },
{ text: "Set your minds on things above.", reference: "Colossians 3:2" },
{ text: "Let your conversation be always full of grace.", reference: "Colossians 4:6" },
{ text: "Be joyful in hope.", reference: "Romans 12:12" },
{ text: "Honor one another above yourselves.", reference: "Romans 12:10" },
{ text: "Do not be overcome by evil.", reference: "Romans 12:21" },
{ text: "For we walk by faith, not by sight.", reference: "2 Corinthians 5:7" },
{ text: "Thanks be to God for His indescribable gift!", reference: "2 Corinthians 9:15" },
{ text: "The Lord is faithful; He will strengthen you.", reference: "2 Thessalonians 3:3" },
{ text: "Encourage one another daily.", reference: "Hebrews 3:13" },
{ text: "Without faith it is impossible to please God.", reference: "Hebrews 11:6" },
{ text: "Jesus Christ is the same yesterday, today, and forever.", reference: "Hebrews 13:8" },
{ text: "Let us run with perseverance.", reference: "Hebrews 12:1" },
{ text: "The Lord is my helper; I will not be afraid.", reference: "Hebrews 13:6" },
{ text: "Draw near to God.", reference: "James 4:8" },
{ text: "Be quick to listen, slow to speak.", reference: "James 1:19" },
{ text: "Every good and perfect gift is from above.", reference: "James 1:17" },
{ text: "Humble yourselves before the Lord.", reference: "James 4:10" },
{ text: "Cast all your anxiety on Him.", reference: "1 Peter 5:7" },
{ text: "Love one another deeply, from the heart.", reference: "1 Peter 1:22" },
{ text: "Be alert and of sober mind.", reference: "1 Peter 5:8" },
{ text: "We love because He first loved us.", reference: "1 John 4:19" },
{ text: "God is greater than our hearts.", reference: "1 John 3:20" },
{ text: "Let us love one another.", reference: "1 John 4:7" },
{ text: "Walk in the light.", reference: "1 John 1:7" },
{ text: "The Lord is slow to anger and rich in love.", reference: "Psalm 145:8" },
{ text: "His mercies are new every morning.", reference: "Lamentations 3:23" },
{ text: "The Lord is good to those who hope in Him.", reference: "Lamentations 3:25" },
{ text: "Blessed are the peacemakers.", reference: "Matthew 5:9" },
{ text: "Blessed are the meek.", reference: "Matthew 5:5" },
{ text: "Blessed are the pure in heart.", reference: "Matthew 5:8" },
{ text: "Let your light shine.", reference: "Matthew 5:16" },
{ text: "Ask and it will be given to you.", reference: "Matthew 7:7" },
{ text: "Come to Me, and I will give you rest.", reference: "Matthew 11:28" },
{ text: "Do not worry about tomorrow.", reference: "Matthew 6:34" },
{ text: "With God all things are possible.", reference: "Matthew 19:26" },
{ text: "The Son of Man came to seek and save the lost.", reference: "Luke 19:10" },
{ text: "Peace I leave with you; My peace I give you.", reference: "John 14:27" },
{ text: "I am the good shepherd.", reference: "John 10:11" },
{ text: "Abide in My love.", reference: "John 15:9" },
{ text: "This is My command: love one another.", reference: "John 15:17" },
{ text: "Do not let your hearts be troubled.", reference: "John 14:1" },
{ text: "The truth will set you free.", reference: "John 8:32" },
{ text: "God demonstrates His love for us.", reference: "Romans 5:8" },
{ text: "The gift of God is eternal life.", reference: "Romans 6:23" },
{ text: "All things work together for good.", reference: "Romans 8:28" },
{ text: "If God is for us, who can be against us?", reference: "Romans 8:31" },
{ text: "Be transformed by the renewing of your mind.", reference: "Romans 12:2" },
{ text: "Love must be sincere.", reference: "Romans 12:9" },
{ text: "Live in harmony with one another.", reference: "Romans 12:16" },
{ text: "Do not be overcome by evil.", reference: "Romans 12:21" },
{ text: "Walk by the Spirit.", reference: "Galatians 5:16" },
{ text: "The fruit of the Spirit is love, joy, peace…", reference: "Galatians 5:22" },
{ text: "Carry each other's burdens.", reference: "Galatians 6:2" },
{ text: "Do good to all people.", reference: "Galatians 6:10" },
{ text: "For by grace you have been saved.", reference: "Ephesians 2:8" },
{ text: "You are God’s masterpiece.", reference: "Ephesians 2:10" },
{ text: "Be kind and compassionate.", reference: "Ephesians 4:32" },
{ text: "Put on the full armor of God.", reference: "Ephesians 6:11" },
{ text: "Rejoice in the Lord always.", reference: "Philippians 4:4" },
{ text: "I can do all things through Christ.", reference: "Philippians 4:13" },
{ text: "Set your hearts on things above.", reference: "Colossians 3:1" },
{ text: "Let the message of Christ dwell richly among you.", reference: "Colossians 3:16" },
{ text: "Be thankful.", reference: "Colossians 3:15" },
{ text: "Fight the good fight of faith.", reference: "1 Timothy 6:12" },
{ text: "The Lord stands by me and gives me strength.", reference: "2 Timothy 4:17" },
{ text: "Let us fix our eyes on Jesus.", reference: "Hebrews 12:2" },
{ text: "The Lord is my helper.", reference: "Hebrews 13:6" }


];

function getDayOfYear(date = new Date()): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff =
    date.getTime() -
    start.getTime() +
    (start.getTimezoneOffset() - date.getTimezoneOffset()) * 60 * 1000;
  return Math.floor(diff / 86400000);
}


const backgroundColors = [
  '#FDE2FF',
  '#FFE6B3',
  '#C8F7FF',
  '#E3FFCF',
  '#FFD6E8',
  '#D9D6FF',
  '#FFF4C2',
  '#CFF5E7',
];


const backgrounds = [
  require('../assets/backgrounds/bg1.png'),
  require('../assets/backgrounds/bg2.png'),
  require('../assets/backgrounds/bg3.png'),
  require('../assets/backgrounds/bg4.png'),
  require('../assets/backgrounds/bg5.png'),
  require('../assets/backgrounds/bg6.png'),
  require('../assets/backgrounds/bg7.png'),
  require('../assets/backgrounds/bg8.png'),
  require('../assets/backgrounds/bg9.png'),
  require('../assets/backgrounds/bg10.png'),
  require('../assets/backgrounds/bg11.png'),
  require('../assets/backgrounds/bg12.png'),
  require('../assets/backgrounds/bg13.png'),
  require('../assets/backgrounds/bg14.png'),
  require('../assets/backgrounds/bg15.png'),
  require('../assets/backgrounds/bg16.png'),
  require('../assets/backgrounds/bg17.png'),
  require('../assets/backgrounds/bg18.png'),
  require('../assets/backgrounds/bg19.png'),
  require('../assets/backgrounds/bg20.png'),
  require('../assets/backgrounds/bg21.png'),
  require('../assets/backgrounds/bg22.png'),
  require('../assets/backgrounds/bg23.png'),
  require('../assets/backgrounds/bg24.png'),
  require('../assets/backgrounds/bg25.png'),
  require('../assets/backgrounds/bg26.png'),
  require('../assets/backgrounds/bg27.png'),
  require('../assets/backgrounds/bg28.png'),
  require('../assets/backgrounds/bg29.png'),
  require('../assets/backgrounds/bg30.png'),
  require('../assets/backgrounds/bg31.png'),
  require('../assets/backgrounds/bg32.png'),
  require('../assets/backgrounds/bg33.png'),
  require('../assets/backgrounds/bg34.png'),
  require('../assets/backgrounds/bg35.png'),
  require('../assets/backgrounds/bg36.png'),
  require('../assets/backgrounds/bg37.png'),
  require('../assets/backgrounds/bg38.png'),
  require('../assets/backgrounds/bg39.png'),
  require('../assets/backgrounds/bg40.png'),
  require('../assets/backgrounds/bg41.png'),
  require('../assets/backgrounds/bg42.png'),
  require('../assets/backgrounds/bg43.png'),
  require('../assets/backgrounds/bg44.png'),
  require('../assets/backgrounds/bg45.png'),
  require('../assets/backgrounds/bg46.png'),
  require('../assets/backgrounds/bg47.png'),
  require('../assets/backgrounds/bg48.png'),
  require('../assets/backgrounds/bg49.png'),
  require('../assets/backgrounds/bg50.png'),
  require('../assets/backgrounds/bg51.png'),
  require('../assets/backgrounds/bg52.png'),
  require('../assets/backgrounds/bg53.png'),
  require('../assets/backgrounds/bg54.png'),
  require('../assets/backgrounds/bg55.png'),
require('../assets/backgrounds/bg56.png'),
require('../assets/backgrounds/bg57.png'),
require('../assets/backgrounds/bg58.png'),
require('../assets/backgrounds/bg59.png'),
require('../assets/backgrounds/bg60.png'),
require('../assets/backgrounds/bg61.png'),
require('../assets/backgrounds/bg62.png'),
require('../assets/backgrounds/bg63.png'),
require('../assets/backgrounds/bg64.png'),
require('../assets/backgrounds/bg65.png'),
require('../assets/backgrounds/bg66.png'),
require('../assets/backgrounds/bg67.png'),
require('../assets/backgrounds/bg68.png'),
require('../assets/backgrounds/bg69.png'),
require('../assets/backgrounds/bg70.png'),
require('../assets/backgrounds/bg71.png'),
require('../assets/backgrounds/bg72.png'),
require('../assets/backgrounds/bg73.png'),
require('../assets/backgrounds/bg74.png'),
require('../assets/backgrounds/bg75.png'),
require('../assets/backgrounds/bg76.png'),
require('../assets/backgrounds/bg77.png'),
require('../assets/backgrounds/bg78.png'),
require('../assets/backgrounds/bg79.png'),
require('../assets/backgrounds/bg80.png'),
require('../assets/backgrounds/bg81.png'),
require('../assets/backgrounds/bg82.png'),
require('../assets/backgrounds/bg83.png'),
require('../assets/backgrounds/bg84.png'),
require('../assets/backgrounds/bg85.png'),
require('../assets/backgrounds/bg86.png'),
require('../assets/backgrounds/bg87.png'),
require('../assets/backgrounds/bg88.png'),
require('../assets/backgrounds/bg89.png'),
require('../assets/backgrounds/bg90.png'),
require('../assets/backgrounds/bg91.png'),
require('../assets/backgrounds/bg92.png'),
require('../assets/backgrounds/bg93.png'),
require('../assets/backgrounds/bg94.png'),
require('../assets/backgrounds/bg95.png'),
require('../assets/backgrounds/bg96.png'),
require('../assets/backgrounds/bg97.png'),
require('../assets/backgrounds/bg98.png'),
require('../assets/backgrounds/bg99.png'),
require('../assets/backgrounds/bg100.png'),
require('../assets/backgrounds/bg101.png'),
require('../assets/backgrounds/bg102.png'),
require('../assets/backgrounds/bg103.png'),
require('../assets/backgrounds/bg104.png'),
require('../assets/backgrounds/bg105.png'),
require('../assets/backgrounds/bg106.png'),
require('../assets/backgrounds/bg107.png'),
require('../assets/backgrounds/bg108.png'),
require('../assets/backgrounds/bg109.png'),
require('../assets/backgrounds/bg110.png'),
require('../assets/backgrounds/bg111.png'),
require('../assets/backgrounds/bg112.png'),
require('../assets/backgrounds/bg113.png'),
require('../assets/backgrounds/bg114.png'),
require('../assets/backgrounds/bg115.png'),
require('../assets/backgrounds/bg116.png'),
require('../assets/backgrounds/bg117.png'),
require('../assets/backgrounds/bg118.png'),
require('../assets/backgrounds/bg119.png'),
require('../assets/backgrounds/bg120.png'),
require('../assets/backgrounds/bg121.png'),
require('../assets/backgrounds/bg122.png'),
require('../assets/backgrounds/bg123.png'),
require('../assets/backgrounds/bg124.png'),
require('../assets/backgrounds/bg125.png'),
require('../assets/backgrounds/bg126.png'),
require('../assets/backgrounds/bg127.png'),
require('../assets/backgrounds/bg128.png'),
require('../assets/backgrounds/bg129.png'),
require('../assets/backgrounds/bg130.png'),
require('../assets/backgrounds/bg131.png'),
require('../assets/backgrounds/bg132.png'),
require('../assets/backgrounds/bg133.png'),
require('../assets/backgrounds/bg134.png'),
require('../assets/backgrounds/bg135.png'),
require('../assets/backgrounds/bg136.png'),
require('../assets/backgrounds/bg137.png'),
require('../assets/backgrounds/bg138.png'),
require('../assets/backgrounds/bg139.png'),
require('../assets/backgrounds/bg140.png'),
require('../assets/backgrounds/bg141.png'),
require('../assets/backgrounds/bg142.png'),
require('../assets/backgrounds/bg143.png'),
require('../assets/backgrounds/bg144.png'),
require('../assets/backgrounds/bg145.png'),
require('../assets/backgrounds/bg146.png'),
require('../assets/backgrounds/bg147.png'),
require('../assets/backgrounds/bg148.png'),
require('../assets/backgrounds/bg149.png'),
require('../assets/backgrounds/bg150.png'),
require('../assets/backgrounds/bg151.png'),
require('../assets/backgrounds/bg152.png'),
require('../assets/backgrounds/bg153.png'),
require('../assets/backgrounds/bg154.png'),
require('../assets/backgrounds/bg155.png'),
require('../assets/backgrounds/bg156.png'),
require('../assets/backgrounds/bg157.png'),
require('../assets/backgrounds/bg158.png'),
require('../assets/backgrounds/bg159.png'),
require('../assets/backgrounds/bg160.png'),
require('../assets/backgrounds/bg161.png'),
require('../assets/backgrounds/bg162.png'),
require('../assets/backgrounds/bg163.png'),
require('../assets/backgrounds/bg164.png'),
require('../assets/backgrounds/bg165.png'),
require('../assets/backgrounds/bg166.png'),
require('../assets/backgrounds/bg167.png'),
require('../assets/backgrounds/bg168.png'),
require('../assets/backgrounds/bg169.png'),
require('../assets/backgrounds/bg170.png'),
require('../assets/backgrounds/bg171.png'),
require('../assets/backgrounds/bg172.png'),
require('../assets/backgrounds/bg173.png'),
require('../assets/backgrounds/bg174.png'),
require('../assets/backgrounds/bg175.png'),
require('../assets/backgrounds/bg176.png'),
require('../assets/backgrounds/bg177.png'),
require('../assets/backgrounds/bg178.png'),
require('../assets/backgrounds/bg179.png'),
require('../assets/backgrounds/bg180.png'),
require('../assets/backgrounds/bg181.png'),
require('../assets/backgrounds/bg182.png'),
require('../assets/backgrounds/bg183.png'),
require('../assets/backgrounds/bg184.png'),
require('../assets/backgrounds/bg185.png'),
require('../assets/backgrounds/bg186.png'),
require('../assets/backgrounds/bg187.png'),
require('../assets/backgrounds/bg188.png'),
require('../assets/backgrounds/bg189.png'),
require('../assets/backgrounds/bg190.png'),
require('../assets/backgrounds/bg191.png'),
require('../assets/backgrounds/bg192.png'),
require('../assets/backgrounds/bg193.png'),
require('../assets/backgrounds/bg194.png'),
require('../assets/backgrounds/bg195.png'),
require('../assets/backgrounds/bg196.png'),
require('../assets/backgrounds/bg197.png'),
require('../assets/backgrounds/bg198.png'),
require('../assets/backgrounds/bg199.png'),
require('../assets/backgrounds/bg200.png'),
require('../assets/backgrounds/bg201.png'),
require('../assets/backgrounds/bg202.png'),
require('../assets/backgrounds/bg203.png'),
require('../assets/backgrounds/bg204.png'),
require('../assets/backgrounds/bg205.png'),
require('../assets/backgrounds/bg206.png'),
require('../assets/backgrounds/bg207.png'),
require('../assets/backgrounds/bg208.png'),
require('../assets/backgrounds/bg209.png'),
require('../assets/backgrounds/bg210.png'),
require('../assets/backgrounds/bg211.png'),
require('../assets/backgrounds/bg212.png'),
require('../assets/backgrounds/bg213.png'),
require('../assets/backgrounds/bg214.png'),
require('../assets/backgrounds/bg215.png'),
require('../assets/backgrounds/bg216.png'),
require('../assets/backgrounds/bg217.png'),
require('../assets/backgrounds/bg218.png'),
require('../assets/backgrounds/bg219.png'),
require('../assets/backgrounds/bg220.png'),
require('../assets/backgrounds/bg221.png'),
require('../assets/backgrounds/bg222.png'),
require('../assets/backgrounds/bg223.png'),
require('../assets/backgrounds/bg224.png'),
require('../assets/backgrounds/bg225.png'),
require('../assets/backgrounds/bg226.png'),
require('../assets/backgrounds/bg227.png'),
require('../assets/backgrounds/bg228.png'),
require('../assets/backgrounds/bg229.png'),
require('../assets/backgrounds/bg230.png'),
require('../assets/backgrounds/bg231.png'),
require('../assets/backgrounds/bg232.png'),
require('../assets/backgrounds/bg233.png'),
require('../assets/backgrounds/bg234.png'),
require('../assets/backgrounds/bg235.png'),
require('../assets/backgrounds/bg236.png'),
require('../assets/backgrounds/bg237.png'),
require('../assets/backgrounds/bg238.png'),
require('../assets/backgrounds/bg239.png'),
require('../assets/backgrounds/bg240.png'),
require('../assets/backgrounds/bg241.png'),
require('../assets/backgrounds/bg242.png'),
require('../assets/backgrounds/bg243.png'),
require('../assets/backgrounds/bg244.png'),
require('../assets/backgrounds/bg245.png'),
require('../assets/backgrounds/bg246.png'),
require('../assets/backgrounds/bg247.png'),
require('../assets/backgrounds/bg248.png'),
require('../assets/backgrounds/bg249.png'),
require('../assets/backgrounds/bg250.png'),
require('../assets/backgrounds/bg251.png'),
require('../assets/backgrounds/bg252.png'),
require('../assets/backgrounds/bg253.png'),
require('../assets/backgrounds/bg254.png'),
require('../assets/backgrounds/bg255.png'),
require('../assets/backgrounds/bg256.png'),
require('../assets/backgrounds/bg257.png'),
require('../assets/backgrounds/bg258.png'),
require('../assets/backgrounds/bg259.png'),
require('../assets/backgrounds/bg260.png'),
require('../assets/backgrounds/bg261.png'),
require('../assets/backgrounds/bg262.png'),
require('../assets/backgrounds/bg263.png'),
require('../assets/backgrounds/bg264.png'),
require('../assets/backgrounds/bg265.png'),
require('../assets/backgrounds/bg266.png'),
require('../assets/backgrounds/bg267.png'),
require('../assets/backgrounds/bg268.png'),
require('../assets/backgrounds/bg269.png'),
require('../assets/backgrounds/bg270.png'),
require('../assets/backgrounds/bg271.png'),
require('../assets/backgrounds/bg272.png'),
require('../assets/backgrounds/bg273.png'),
require('../assets/backgrounds/bg274.png'),
require('../assets/backgrounds/bg275.png'),
require('../assets/backgrounds/bg276.png'),
require('../assets/backgrounds/bg277.png'),
require('../assets/backgrounds/bg278.png'),
require('../assets/backgrounds/bg279.png'),
require('../assets/backgrounds/bg280.png'),
require('../assets/backgrounds/bg281.png'),
require('../assets/backgrounds/bg282.png'),
require('../assets/backgrounds/bg283.png'),
require('../assets/backgrounds/bg284.png'),
require('../assets/backgrounds/bg285.png'),
require('../assets/backgrounds/bg286.png'),
require('../assets/backgrounds/bg287.png'),
require('../assets/backgrounds/bg288.png'),
require('../assets/backgrounds/bg289.png'),
require('../assets/backgrounds/bg290.png'),
require('../assets/backgrounds/bg291.png'),
require('../assets/backgrounds/bg292.png'),
require('../assets/backgrounds/bg293.png'),
require('../assets/backgrounds/bg294.png'),
require('../assets/backgrounds/bg295.png'),
require('../assets/backgrounds/bg296.png'),
require('../assets/backgrounds/bg297.png'),
require('../assets/backgrounds/bg298.png'),
require('../assets/backgrounds/bg299.png'),
require('../assets/backgrounds/bg300.png'),
require('../assets/backgrounds/bg301.png'),
require('../assets/backgrounds/bg302.png'),
require('../assets/backgrounds/bg303.png'),
require('../assets/backgrounds/bg304.png'),
require('../assets/backgrounds/bg305.png'),
require('../assets/backgrounds/bg306.png'),
require('../assets/backgrounds/bg307.png'),
require('../assets/backgrounds/bg308.png'),
require('../assets/backgrounds/bg309.png'),
require('../assets/backgrounds/bg310.png'),
require('../assets/backgrounds/bg311.png'),
require('../assets/backgrounds/bg312.png'),
require('../assets/backgrounds/bg313.png'),
require('../assets/backgrounds/bg314.png'),
require('../assets/backgrounds/bg315.png'),
require('../assets/backgrounds/bg316.png'),
require('../assets/backgrounds/bg317.png'),
require('../assets/backgrounds/bg318.png'),
require('../assets/backgrounds/bg319.png'),
require('../assets/backgrounds/bg320.png'),
require('../assets/backgrounds/bg321.png'),
require('../assets/backgrounds/bg322.png'),
require('../assets/backgrounds/bg323.png'),
require('../assets/backgrounds/bg324.png'),
require('../assets/backgrounds/bg325.png'),
require('../assets/backgrounds/bg326.png'),
require('../assets/backgrounds/bg327.png'),
require('../assets/backgrounds/bg328.png'),
require('../assets/backgrounds/bg329.png'),
require('../assets/backgrounds/bg330.png'),
require('../assets/backgrounds/bg331.png'),
require('../assets/backgrounds/bg332.png'),
require('../assets/backgrounds/bg333.png'),
require('../assets/backgrounds/bg334.png'),
require('../assets/backgrounds/bg335.png'),
require('../assets/backgrounds/bg336.png'),
require('../assets/backgrounds/bg337.png'),
require('../assets/backgrounds/bg338.png'),
require('../assets/backgrounds/bg339.png'),
require('../assets/backgrounds/bg340.png'),
require('../assets/backgrounds/bg341.png'),
require('../assets/backgrounds/bg342.png'),
require('../assets/backgrounds/bg343.png'),
require('../assets/backgrounds/bg344.png'),
require('../assets/backgrounds/bg345.png'),
require('../assets/backgrounds/bg346.png'),
require('../assets/backgrounds/bg347.png'),
require('../assets/backgrounds/bg348.png'),
require('../assets/backgrounds/bg349.png'),
require('../assets/backgrounds/bg350.png'),
require('../assets/backgrounds/bg351.png'),
require('../assets/backgrounds/bg352.png'),
require('../assets/backgrounds/bg353.png'),
require('../assets/backgrounds/bg354.png'),
require('../assets/backgrounds/bg355.png'),
require('../assets/backgrounds/bg356.png'),
require('../assets/backgrounds/bg357.png'),
require('../assets/backgrounds/bg358.png'),
require('../assets/backgrounds/bg359.png'),
require('../assets/backgrounds/bg360.png'),
require('../assets/backgrounds/bg361.png'),
require('../assets/backgrounds/bg362.png'),
require('../assets/backgrounds/bg363.png'),
require('../assets/backgrounds/bg364.png'),
require('../assets/backgrounds/bg365.png'),





// if you add more later:
  // require('../assets/backgrounds/bg366.png'),
  // require('../assets/backgrounds/bg367.png'),

];

// floating pastel blobs behind the content
const FloatingShapes = () => {
  return (
    <View style={styles.shapesContainer}>
      <View style={[styles.shape, styles.shape1]} />
      <View style={[styles.shape, styles.shape2]} />
      <View style={[styles.shape, styles.shape3]} />
    </View>
  );
};
export default function Index() {
  const [verseIndex, setVerseIndex] = useState(0);

  // nav helpers
  const prevVerse = () => {
    setVerseIndex(prev => (prev - 1 + verses.length) % verses.length);
  };

  const nextVerse = () => {
    setVerseIndex(prev => (prev + 1) % verses.length);
  };

  // show day number (1–365)
  const dayNumber = (verseIndex % 365) + 1;

  // ----- SWIPE SETUP -----
  const SWIPE_THRESHOLD = 40;

  const panResponder = useRef(
    PanResponder.create({
      // start handling if the user moves their finger horizontally
      onMoveShouldSetPanResponder: (_evt, gestureState) =>
        Math.abs(gestureState.dx) > 10,
      onMoveShouldSetPanResponderCapture: (_evt, gestureState) =>
        Math.abs(gestureState.dx) > 10,

      onPanResponderRelease: (_evt, gestureState) => {
        if (gestureState.dx > SWIPE_THRESHOLD) {
          // swipe right → previous verse
          prevVerse();
        } else if (gestureState.dx < -SWIPE_THRESHOLD) {
          // swipe left → next verse
          nextVerse();
        }
      },
    })
  ).current;

  // pick verse + background
  const verse = verses[verseIndex];
  const bgIndex = verseIndex % backgrounds.length;

  return (
    <ImageBackground
      source={backgrounds[bgIndex]}
      style={styles.background}
      resizeMode="cover"
      {...panResponder.panHandlers}
    >
      <FloatingShapes />

      <SafeAreaView style={styles.safe}>
        <StatusBar barStyle="light-content" />

        <View style={styles.centerWrapper}>
          {/* Day pill */}
          <View style={styles.dayPill}>
            <Text style={styles.dayText}>Day {dayNumber} of 365</Text>
          </View>

          {/* Verse card (centered) */}
          <View style={styles.card}>
            <Text style={styles.verseText}>{verse.text}</Text>
            <Text style={styles.reference}>{verse.reference}</Text>
          </View>

          {/* Buttons */}
          <View style={styles.buttons}>
            <View style={styles.row}>
              <TouchableOpacity style={styles.smallButton} onPress={prevVerse}>
                <Text style={styles.smallButtonText}>◀︎ Previous</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.smallButton} onPress={nextVerse}>
                <Text style={styles.smallButtonText}>Next ▶︎</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </SafeAreaView>
    </ImageBackground>
  );
}

const styles = StyleSheet.create({
  background: {
    flex: 1,
  },

  safe: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.15)', // tint over the image
  },

  // wrapper that centers the verse in the middle
  centerWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },

  dayPill: {
    marginBottom: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },

  dayText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#555',
  },

  card: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 18,
    padding: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
    maxWidth: 340,
  },

  verseText: {
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    color: '#333',
  },

  reference: {
    marginTop: 14,
    fontSize: 16,
    textAlign: 'center',
    color: '#666',
  },

  buttons: {
    marginTop: 24,
  },

  row: {
    flexDirection: 'row',
    justifyContent: 'center',
  },

  smallButton: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginHorizontal: 6,
  },

  smallButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },

  // floating blobs
  shapesContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },

  shape: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 200,
    opacity: 0.22,
  },

  shape1: {
    backgroundColor: '#FFD6E8', // pink
    top: -40,
    left: -90,
  },

  shape2: {
    backgroundColor: '#D6F2FF', // blue
    bottom: 90,
    right: -70,
  },

  shape3: {
    backgroundColor: '#FFF8C9', // yellow
    top: 280,
    left: 40,
  },
});

   